CREATE TABLE User (
 ID INT NOT NULL AUTO_INCREMENT UNIQUE,
 First_Name VARCHAR(25) NOT NULL,
 Last_Name VARCHAR(25) NOT NULL,
 Username VARCHAR(20) NOT NULL,
 Password VARCHAR(20) NOT NULL,
 Email VARCHAR(20) NOT NULL,
 Admin CHAR(1),
 PRIMARY KEY( ID )
);

CREATE TABLE Service (
 Service_ID INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(20) NOT NULL UNIQUE,
 PRIMARY KEY(Service_ID)
);

CREATE TABLE Package (
 Package_ID INT NOT NULL AUTO_INCREMENT,
 Service_ID INT NOT NULL,
 Name VARCHAR(20) NOT NULL UNIQUE,
 Price INT NOT NULL,
 PRIMARY KEY(Package_ID, Service_ID)
);

CREATE TABLE Shows (
 Show_ID INT NOT NULL AUTO_INCREMENT,
 Package_ID INT NOT NULL,
 Name VARCHAR(20) NOT NULL UNIQUE,
 Genre VARCHAR(20) NOT NULL UNIQUE,
 Season INT NOT NULL,
 Network_ID INT NOT NULL,
 PRIMARY KEY (Show_ID, Package_ID, Season)
);

CREATE TABLE Network (
 Network_ID INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(20) NOT NULL UNIQUE,
 PRIMARY KEY (Network_ID)
);